name: Build TShock

on:
  workflow_dispatch:
#     inputs:
#       v4ts:
#         description: 'Version of TShock.'
#         required: true
#         default: 4.5.17
#       v4tr:
#         description: 'Version of Terraria.'
#         required: true
#         default: 1.4.3.6

jobs:
  build-tshock:
    name: build tshock
    runs-on: ubuntu-latest

    steps:
      - name: Set Var
        id  : set_var
        run : |
              echo ::set-output name=download_url::`curl -s https://api.github.com/repos/Pryaxis/TShock/releases/latest | grep browser_download_url | grep zip | cut -d '"' -f 4` /
              echo ::set-output name=tshock_version::`curl -s https://api.github.com/repos/Pryaxis/TShock/releases/latest | grep browser_download_url | grep zip | cut -d '"' -f 4 | sed -nr 's/^[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p'`
      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set Version
        run : |
              sed -i "?^ADD http?c ADD ${{ steps.set_var.outputs.download_url }}?" TShock/Dockerfile
              cat TShock/Dockerfile
              
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./TShock
          file: TShock/Dockerfile
          platforms: linux/amd64 # ,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ky9i/tshock:latest
            ky9i/tshock:tshock-latest
            ky9i/tshock:${{ steps.set_var.outputs.tshock_version }}
            
      - name: Commit
        run : |
              git config user.name 自动提交
              git config user.email 自动提交
              git add TShock/Dockerfile
              git commit -m "`TZ=Asia/Shanghai date "+%Y-%m-%d %H:%M:%S"` GitHub Actions 自动提交"
              git push
